extends RefCounted
## Visual timelines only. The caller supplies combat geometry; no damage or RNG here.
var director
var center=Vector2(360,493)
var mint=Color("8ef8dd")
var gold=Color("ffe18a")
var ice=Color("a3ecff")
var violet=Color("c6a1ff")
var orange=Color("ffa85a")
var acid=Color("88ea61")
var cyan=Color("42e6cf")
var path: Array=[Vector2(360,900),Vector2(675,460),Vector2(517.5,240)]

func cue(kind: String, delay: float=0.0, tint: Color=Color.WHITE, offset: Vector2=Vector2.ZERO, extra: Dictionary={}):
	director.later(delay,kind,center+offset,tint,extra)
func ring(delay: float=0.0, tint: Color=Color("86dfff")):
	for i in range(3): cue("resonance",delay+i*.13,tint)
func blast(delay: float=0.0, tint: Color=Color("ffbf69"), diagonal: bool=true):
	var offsets=[Vector2(-92,0),Vector2(92,0),Vector2(0,-75),Vector2(0,75)]
	if diagonal: offsets.append_array([Vector2(-92,-75),Vector2(92,-75),Vector2(-92,75),Vector2(92,75)])
	for i in range(offsets.size()): cue("bomb_drop",delay+i*.035,tint,offsets[i])
func bolt(delay: float=0.0,tint: Color=Color("c6a1ff"),count: int=4):
	var previous=center-Vector2(0,230)
	for i in range(count):
		var target=center+Vector2((i%3-1)*92,(i/3)*75)
		director.later(delay+i*.09,"bolt",target,tint,{"from":previous,"to":target})
		previous=target
func freeze(delay: float=0.0,count: int=5):
	for i in range(count): cue("ice",delay+i*.08,Color.WHITE,Vector2((i-2)*92,0))
func coins(delay: float=0.0):
	cue("treasure",delay)
	for i in range(7): cue("coin",delay+.18+i*.025,Color.WHITE,Vector2.ZERO,{"offset":Vector2((i-3)*18,-85)})
func arrow(delay: float=0.0,tint: Color=Color("a3ecff"),offset: Vector2=Vector2.ZERO):
	director.later(delay,"arrow_flight",center+Vector2(-70,350)+offset,tint,{"to":center+Vector2(60,-220)+offset,"travel":0.9})
func split(delay: float=0.0,tint: Color=Color("42e6cf"),size: float=0.15):
	for side in [-1,1]: cue("orb_flight",delay,tint,Vector2.ZERO,{"to":center+Vector2(side*120,-220),"scale":size,"travel":0.7})
func wall(delay: float=0.0,tint: Color=Color("ff4a21")):
	director.later(delay,"orb_flight",Vector2(45,690),tint,{"to":Vector2(675,center.y),"travel":0.45})
	director.later(delay+.45,"power",Vector2(675,center.y),tint)
	director.later(delay+.45,"orb_flight",Vector2(675,center.y),tint,{"to":center-Vector2(120,130),"travel":0.45})
func rebound(delay: float=0.0,tint: Color=Color("8ef8dd"),as_arrow: bool=false):
	director.later(delay,"orb_flight",Vector2(160,590),Color.WHITE,{"to":Vector2(360,880),"travel":0.45})
	director.later(delay+.45,"ricochet",Vector2(360,855),tint)
	director.later(delay+.45,"arrow_flight" if as_arrow else "orb_flight",Vector2(360,880),tint,{"to":Vector2(560,590),"travel":0.45})
func beam(delay: float=0.0,tint: Color=Color("ff9bbc")):
	for i in range(path.size()-1): director.later(delay+i*.05,"laser",path[i],tint,{"from":path[i],"to":path[i+1]})
func cross(delay: float=0.0,tint: Color=Color("b6efff")):
	cue("pulse",delay,tint,Vector2.ZERO,{"from":Vector2(45,center.y),"to":Vector2(675,center.y)})
	cue("pulse",delay,tint,Vector2.ZERO,{"from":Vector2(center.x,240),"to":Vector2(center.x,910)})
func missiles(delay: float=0.0,count: int=8,focused: bool=false,tint: Color=Color.WHITE):
	for i in range(count):
		var target=center if focused else center+Vector2((i%5-2)*92,(i/5)*75)
		director.later(delay+i*.08,"missile",target,tint,{"from":Vector2(45 if i%2==0 else 675,850)})
func mark(delay: float=0.0): cue("mark",delay,Color("ff677a"))
func action(kind: String, delay: float=0.0): cue(kind,delay,gold if kind=="critical" else violet)

func play(target_director, id: String, geometry: Dictionary={}):
	director=target_director
	center=geometry.get("target",Vector2(360,493))
	path=geometry.get("path",[Vector2(360,900),Vector2(675,460),Vector2(517.5,240)])
	match id:
		"power__pierce": arrow(); cue("power",.35,orange); cue("power",.5,orange,Vector2(30,-90)); beam(.75,orange)
		"power__blast": cue("power",0,orange); blast(.16)
		"power__lightning": cue("power",0,orange); bolt(.2,violet,4)
		"power__frost": freeze(); cue("power",.45,orange); cue("shatter",.50,ice); blast(.55,ice,false)
		"power__critical": cue("power",0,orange); action("critical",.08); ring(.2,gold)
		"power__wall": wall(); cue("power",.85,orange); cue("explosion",.92,orange,Vector2.ZERO,{"size":160})
		"power__corrosion": cue("corrosion",0,acid); cue("corrosion",.15,acid); cue("explosion",.45,acid)
		"power__bounty": mark(); cue("power",.25,orange); coins(.35)
		"power__split": cue("power",0,orange); split(.13,orange,.23)
		"power__resonance": ring(0,orange); cue("power",.48,orange)
		"power__ricochet": rebound(0,orange); cue("power",.94,orange,Vector2(180,100))
		"pierce__blast": arrow(); blast(.32)
		"pierce__lightning": arrow(); bolt(.65,ice,5)
		"pierce__frost": arrow(0,ice); freeze(.30); cue("shatter",.7,ice)
		"pierce__critical": arrow(); action("critical",.35); cue("pierce",.38,gold)
		"pierce__wall": wall(0,ice); arrow(.45); action("critical",.75)
		"pierce__corrosion": arrow(0,acid); cue("corrosion",.3,acid); cue("corrosion",.5,acid,Vector2(20,-75))
		"pierce__bounty": mark(); arrow(.2,gold); coins(.8)
		"pierce__split": arrow(); arrow(.34,cyan,Vector2(-70,0)); arrow(.34,cyan,Vector2(70,0))
		"pierce__resonance": arrow(); ring(.4,ice)
		"pierce__ricochet": rebound(0,ice,true)
		"blast__lightning": blast(); bolt(.6,violet,5)
		"blast__frost": blast(); freeze(.45); blast(.85,ice,false)
		"blast__critical": action("critical"); blast(.15,gold); cue("explosion",.55,gold,Vector2.ZERO,{"size":170})
		"blast__wall": wall(); blast(.9,orange)
		"blast__corrosion": blast(); cue("corrosion",.45,acid); cue("corrosion",.55,acid,Vector2(92,0))
		"blast__bounty": coins(); blast(.4,gold)
		"blast__split": blast(); split(.5); split(.75,cyan,.13)
		"blast__resonance": ring(); blast(.45)
		"blast__ricochet": rebound(); blast(.95,orange,false)
		"lightning__frost": bolt(); freeze(.18)
		"lightning__critical": action("critical"); bolt(.15,gold,3)
		"lightning__wall": wall(); bolt(.50,violet,4)
		"lightning__corrosion": bolt(0,acid,5); cue("corrosion",.4,acid)
		"lightning__bounty": bolt(); mark(.35); coins(.6)
		"lightning__split": split(); bolt(.55,violet,2)
		"lightning__resonance": ring(); bolt(.40,violet,4)
		"lightning__ricochet": rebound(0,violet); bolt(.6,violet,3)
		"frost__critical": freeze(); action("critical",.4); cue("shatter",.45,ice)
		"frost__wall": wall(0,ice); freeze(.50); arrow(.55,ice)
		"frost__corrosion": freeze(); cue("corrosion",.3,acid); cue("shatter",.9,ice)
		"frost__bounty": freeze(); coins(.55); freeze(.8)
		"frost__split": split(0,cyan); freeze(.65)
		"frost__resonance": freeze(); ring(.3,ice)
		"frost__ricochet": rebound(0,ice); freeze(.85)
		"critical__wall": wall(0,gold); action("critical",.87)
		"critical__corrosion": cue("corrosion",0,acid); action("critical",.3); cue("explosion",.4,acid)
		"critical__bounty": action("critical"); coins(.2); coins(.6)
		"critical__split": split(0,gold); action("critical",.6)
		"critical__resonance": ring(0,gold); action("critical",.4)
		"critical__ricochet": rebound(0,gold); action("critical",.95)
		"wall__corrosion": wall(0,acid); cue("corrosion",.5,acid,Vector2(92,0)); cue("corrosion",.6,acid)
		"wall__bounty": wall(0,gold); coins(.9)
		"wall__split": wall(); split(.5)
		"wall__resonance": wall(); ring(.5)
		"wall__ricochet": wall(); rebound(.55,orange)
		"corrosion__bounty": mark(); cue("corrosion",.2,acid); coins(.6)
		"corrosion__split": split(0,cyan); cue("corrosion",.6,acid,Vector2(-92,-75)); cue("corrosion",.6,acid,Vector2(92,-75))
		"corrosion__resonance": cue("corrosion",0,acid); ring(.25,acid)
		"corrosion__ricochet": rebound(0,acid); cue("corrosion",.9,acid)
		"bounty__split": split(0,gold); coins(.6); mark(1.1)
		"bounty__resonance": mark(); ring(.2,gold); coins(.55)
		"bounty__ricochet": rebound(0,gold); coins(.9)
		"split__resonance": ring(); split(.4)
		"split__ricochet": rebound(0,cyan); split(.65)
		"resonance__ricochet": rebound(); ring(.9)
		"laser__bomb": beam(); blast(.35)
		"laser__freeze": beam(0,ice); freeze(.3)
		"laser__mark": mark(); beam(.25,gold); cue("power",.45,gold)
		"laser__overclock": beam(); beam(.28); beam(.56); action("overclock",.1)
		"laser__pulse": beam(); cross(.25)
		"laser__missile": beam(); missiles(.4,6)
		"laser__echo": beam(); beam(.5,violet); beam(.9,violet)
		"bomb__freeze": blast(); freeze(.45)
		"bomb__mark": mark(); missiles(.2,6,true)
		"bomb__overclock": action("overclock"); blast(.2); blast(.8)
		"bomb__pulse": blast(); cross(.45)
		"bomb__missile": cue("bomb_drop"); missiles(.38,8)
		"bomb__echo": blast(); blast(.9,violet)
		"freeze__mark": freeze(); mark(.4)
		"freeze__overclock": freeze(); action("overclock",.5); split(.7,ice)
		"freeze__pulse": freeze(); cross(.55,ice); ring(.6,ice)
		"freeze__missile": freeze(); missiles(.4,8,false,ice)
		"freeze__echo": freeze(); action("echo",.7); freeze(1.0)
		"mark__overclock": mark(); action("overclock",.2); missiles(.3,6,true)
		"mark__pulse": mark(); cross(.25,Color("ff677a")); cue("explosion",.3,gold)
		"mark__missile": mark(); missiles(.2,10,true)
		"mark__echo": mark(); action("echo",.5); mark(1.0)
		"overclock__pulse": action("overclock"); cross(.2,orange); cross(.5,orange); cross(.75,orange)
		"overclock__missile": action("overclock"); missiles(.2,12,false,orange)
		"overclock__echo": action("overclock"); split(.2,orange); action("echo",.85); split(1.0,violet)
		"pulse__missile": cross(); missiles(.35,8)
		"pulse__echo": cross(); ring(.3); cross(.6,violet); cross(1.0,violet)
		"missile__echo": missiles(0,8); missiles(.8,6,false,ice); missiles(1.5,4,false,violet)
		_: push_error("Missing fusion choreography: "+id)
